CREATE OR REPLACE PROCEDURE GET_TOTAL_PAY (
    PI_NU_ID PAYROLL.NU_ID%TYPE,
    PI_JOB_ID PAYROLL.JOB_ID%TYPE)
IS
    v_total_pay NUMBER;
BEGIN
    SELECT SUM(GROSS_PAY) INTO v_total_pay
    FROM PAYROLL
    WHERE NU_ID = PI_NU_ID
      AND JOB_ID = PI_JOB_ID
      AND START_DATE >= TO_DATE('2023-11-01', 'YYYY-MM-DD')
      AND END_DATE <= (SELECT MAX(END_DATE) FROM PAYROLL);

    DBMS_OUTPUT.PUT_LINE('Total Pay for NU_ID ' || PI_NU_ID || ' and JOB_ID ' || PI_JOB_ID || ' is: ' || v_total_pay);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No data found for the provided NU_ID and JOB_ID.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An error occurred: ' || SQLERRM);
END GET_TOTAL_PAY;
/


EXEC GET_TOTAL_PAY(1538793, 'J0021');
EXEC GET_TOTAL_PAY(6479036, 'J0011');

--SELECT * FROM STUDENT_JOBS;






