DROP SEQUENCE ATTENDANCE_SEQ;

DROP SEQUENCE PAYROLL_SEQ;

DROP TABLE PAYROLL CASCADE CONSTRAINTS;

DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;

DROP TABLE STUDENT_JOBS CASCADE CONSTRAINTS;

DROP TABLE STUDENTS CASCADE CONSTRAINTS;

DROP TABLE JOBS CASCADE CONSTRAINTS;

DROP TABLE SUPERVISOR CASCADE CONSTRAINTS;

DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;

DROP USER ADMIN_SUPERVISOR CASCADE;

DROP USER NA_SUPERVISOR CASCADE;

DROP USER STUDENT_USER CASCADE;

DROP VIEW CURRENT_SALARY;

DROP VIEW VIEW_DEPARTMENT;

DROP VIEW VIEW_SUPERVISOR;

DROP VIEW VIEW_JOBS;

DROP VIEW VIEW_STUDENT_JOBS;

DROP VIEW VIEW_STUDENTS;

DROP VIEW VIEW_ATTENDANCE;

DROP VIEW VIEW_PAYROLL;

--SELECT * FROM USER_TABLES;


