CREATE OR REPLACE TRIGGER Set_Hourly_Wage
BEFORE INSERT ON JOBS
FOR EACH ROW
BEGIN
    CASE
        WHEN :NEW.BAND = 'A' THEN :NEW.HOURLY_WAGE := 17;
        WHEN :NEW.BAND = 'B' THEN :NEW.HOURLY_WAGE := 16;
        WHEN :NEW.BAND = 'C' THEN :NEW.HOURLY_WAGE := 15;
    END CASE;
END;
/



