SET SERVEROUTPUT ON;

DECLARE
    user_exists NUMBER;
BEGIN
  
    SELECT COUNT(*) INTO user_exists FROM dba_users WHERE username = 'ADMIN_SUPERVISOR';

   
    IF user_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP USER ADMIN_SUPERVISOR CASCADE';
        DBMS_OUTPUT.PUT_LINE('User ADMIN_SUPERVISOR dropped.');
    END IF;

 
    EXECUTE IMMEDIATE 'CREATE USER ADMIN_SUPERVISOR IDENTIFIED BY Cccccccc2023#';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO ADMIN_SUPERVISOR';
    EXECUTE IMMEDIATE 'ALTER USER ADMIN_SUPERVISOR QUOTA 1m ON DATA';

   

    DBMS_OUTPUT.PUT_LINE('User ADMIN_SUPERVISOR created and privileges granted.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An unexpected error occurred: ' || SQLERRM);
END;
/








--SELECT * FROM DBA_USERS;


/*CREATE USER NA_SUPERVISOR IDENTIFIED BY Duracell2023##;
GRANT CONNECT, RESOURCE TO NA_SUPERVISOR;
ALTER USER NA_SUPERVISOR QUOTA 1m ON DATA;


CREATE USER STUDENT_USER IDENTIFIED BY Duracell2023###;
GRANT CONNECT, RESOURCE TO STUDENT_USER;
ALTER USER STUDENT_USER QUOTA 1m ON DATA;*/

