SET SERVEROUTPUT ON;

DECLARE
    user_exists NUMBER;
BEGIN
    -- Check if the user exists
    SELECT COUNT(*) INTO user_exists FROM DBA_USERS WHERE username = 'ADMIN_SUPERVISOR';

    -- Drop the user if it exists
    IF user_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP USER ADMIN_SUPERVISOR CASCADE';
        DBMS_OUTPUT.PUT_LINE('User ADMIN_SUPERVISOR dropped.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('User ADMIN_SUPERVISOR does not exist. Proceeding to create.');
    END IF;

    -- Creating the user
    EXECUTE IMMEDIATE 'CREATE USER ADMIN_SUPERVISOR IDENTIFIED BY AstonCC2023#';
    DBMS_OUTPUT.PUT_LINE('User ADMIN_SUPERVISOR created.');

    -- Granting the privileges
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO ADMIN_SUPERVISOR';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE USER, DROP USER, ALTER USER,CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER, CREATE SEQUENCE, CREATE SYNONYM TO ADMIN_SUPERVISOR';
    DBMS_OUTPUT.PUT_LINE('Privileges granted to ADMIN_SUPERVISOR.');

   
    EXECUTE IMMEDIATE 'ALTER USER ADMIN_SUPERVISOR QUOTA 1m ON DATA';
    DBMS_OUTPUT.PUT_LINE('Quota set for ADMIN_SUPERVISOR on DATA tablespace.');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An unexpected error occurred: ' || SQLERRM);
END;
/











