SET SERVEROUTPUT ON;

BEGIN
    -- Delete NA_SUPERVISOR user if exists
    BEGIN
        EXECUTE IMMEDIATE 'DROP USER NA_SUPERVISOR CASCADE';
        DBMS_OUTPUT.PUT_LINE('User NA_SUPERVISOR dropped.');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('User NA_SUPERVISOR does not exist or cannot be dropped.');
    END;

    -- Create NA_SUPERVISOR user
    EXECUTE IMMEDIATE 'CREATE USER NA_SUPERVISOR IDENTIFIED BY Duracell2023#';
    DBMS_OUTPUT.PUT_LINE('User NA_SUPERVISOR created.');

    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO NA_SUPERVISOR';
    DBMS_OUTPUT.PUT_LINE('Basic privileges granted to NA_SUPERVISOR.');

    -- Grant access to only the Attendance table, Attendance view to NA_SUPERVISOR
    EXECUTE IMMEDIATE 'GRANT INSERT, SELECT ON ATTENDANCE TO NA_SUPERVISOR';
    EXECUTE IMMEDIATE 'GRANT SELECT ON VIEW_ATTENDANCE TO NA_SUPERVISOR';
    DBMS_OUTPUT.PUT_LINE('Access to ATTENDANCE table and VIEW_ATTENDANCE view granted to NA_SUPERVISOR.');

    -- Delete STUDENT_USER user if exists
    BEGIN
        EXECUTE IMMEDIATE 'DROP USER STUDENT_USER CASCADE';
        DBMS_OUTPUT.PUT_LINE('User STUDENT_USER dropped.');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('User STUDENT_USER does not exist or cannot be dropped.');
    END;

    -- Create STUDENT_USER user
    EXECUTE IMMEDIATE 'CREATE USER STUDENT_USER IDENTIFIED BY Duracell2023#';
    DBMS_OUTPUT.PUT_LINE('User STUDENT_USER created.');

    -- Grant SELECT ON CURRENT_SALARY VIEW TO STUDENT_USER
    -- Make sure the CURRENT_SALARY view exists before running this grant
    EXECUTE IMMEDIATE 'GRANT SELECT ON CURRENT_SALARY TO STUDENT_USER';
    DBMS_OUTPUT.PUT_LINE('SELECT privilege on CURRENT_SALARY view granted to STUDENT_USER.');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An unexpected error occurred: ' || SQLERRM);
END;
/

